modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ichttft/firstaid"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/first-aid"
logoFile="firstaid_logo.png"
authors="ichttt, Rui"
description='''First Aid is a game changing mod focused around a new health system.'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playerrevive"
type="optional"
versionRange="[2.0.24,)"
ordering="NONE"
side="BOTH"
